config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users
  resources :riddles
  resources :scores

  post "/riddles/:id" => 'riddles#answer'
  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/riddle.rb
class Riddle < ApplicationRecord
    has_many :scores
    belongs_to :user, :optional => true
end

app/models/score.rb
class Score < ApplicationRecord
    belongs_to :riddle, :optional => true
    belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_many :riddles
    has_many :scores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    def fetch_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present?
    end

    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/riddles_controller.rb
class RiddlesController < ApplicationController
  before_action :check_for_login

  def index
    @riddles = Riddle.all
  end

  def new
    @riddle = Riddle.new
  end

  def create
    riddle = Riddle.create riddle_params
    @current_user.riddles << riddle
    redirect_to riddles_path
  end

  def edit
    @riddle = Riddle.find params[:id]
    if @riddle.user_id != @current_user.id
      redirect_to riddles_path
    end
  end

  def update
    riddle = Riddle.find params[:id]
    riddle.update riddle_params
    redirect_to riddle
  end

  def show
    @riddle = Riddle.find params[:id]
    session[:start_time] = Time.new #once user presses link of the show link it logs a time
  end

  def answer
    @riddle = Riddle.find params[:id]
    riddle_answer = @riddle.answer
    if riddle_answer.downcase == params[:answer].downcase #if win
      score = Time.new - session[:start_time].to_datetime # when answered correctly it subtracts the time now from when they started.
      new_score = Score.new(:point => score.round(3), :user_id => @current_user.id, :riddle_id => @riddle.id)
      new_score.save
      redirect_to score_path #goes into scores#show for the particular riddle
    else #if loss
      @flash_alert = "Wrong! Guess again" #this does not work TODO
      render :show
    end
  end

  def destroy
    riddle = Riddle.find params[:id]
    riddle.destroy
    redirect_to riddles_path
  end

  private
  def riddle_params
    params.require(:riddle).permit(:name, :question, :answer, :user_id, :answer)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
    
    @riddle = Riddle.find params[:id] #associated RIDDLES INFO
    @user = User.all #make it so that only users who played show up on scores
    @scores = Score.all.order("point")
    @score = Score.last.point #grabs the most recent score
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Sorry, login failed."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
    User.create user_params
    session[:user_id] = @user.id
    redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
    if @current_user.id != @user.id
      redirect_to root_path
    end
  end

  def update
    @user = User.find params[:id]
    @user.update user_params
    redirect_to user_path
  end

  def show
    @user = User.find params[:id]
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    user.riddles.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :image, :info)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/riddle_helper.rb
module RiddleHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="icon" href="https://i.imgur.com/w9fwa8B.png">
    <title>Ridlr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet"> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav> 
      <%= link_to 'Home', root_path %>
      <% if @current_user.present? %>
        <%= link_to "Admin", users_path if @current_user.admin? %>
        <%= link_to "Profile", user_path(@current_user) %>
        <%= link_to "Make Riddle", new_riddle_path %>
        <%= link_to "All Riddles", riddles_path %>
        <%= link_to "Logout #{ @current_user.email }", login_path, :method => "delete", :class => 'logout' %>
      <% else %>
      <%= link_to 'Sign Up', new_user_path %>
      <%= link_to 'Log in', login_path %>
      <% end %>
    </nav>
    <div class="allpages">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% if @current_user.present?%>
    <h1 class="welcome">Hi there <%= @current_user.email %></h1>
    
    <div class="instructions">
    <h2>Welcome to the Ridlr</h2>
    <p>This is a collaborative platform for users to connect and share riddles!</p>

    <h2> How to Play</h2>
    <p>Head over to the make Riddles tab</p>
    <p>Fill out the form to make your very first riddle!</p>
    <p>Once you are finished you can head over to our all riddles section.</p>
    <p>You will be able to play other riddlers games!</p>
    <p>If you like the riddle, you can navigate to their profile and see what other riddles they have made!</p>
    <br>
    <p>Enjoy and have fun!</p>
    </div>
<% else %>
    <h1 class="welcome">Welcome! Please sign up!</h1>

    <div class="instructions">
    <h3>Welcome to the Ridlr</h3>
    <p>This is a collaborative platform for users to connect and share riddles!</p>

    <h3> How to Play</h3>

    <p>Make sure you have created and signed into your account.</p>
    <p>Head over to the make Riddles tab</p>
    <p>Fill out the form to make your very first riddle!</p>
    <p>Once you are finished you can head over to our all riddles section.</p>
    <p>You will be able to play other riddlers games!</p>
    <p>If you like the riddle, you can navigate to their profile and see what other riddles they have made!</p>
    <br>
    <p>Enjoy and have fun!</p>
    </div>
<% end %>

app/views/riddles/_form.html.erb
<%= form_for @riddle do |f| %>

    <%= f.label :name_of_riddle %>
    <%= f.text_field :name %>

    <%= f.label :question %>
    <%= f.text_area :question, :class => "questionbox"%>

    <%= f.label :answer %>
    <%= f.text_field :answer %>

    <%= f.submit :class => "postbutton" %>
<% end %>

app/views/riddles/edit.html.erb
<h1 class="bouncingheadings">Edit Riddle</h1>

<%= render :partial => 'form' %>

<%= button_to "Delete Riddle", @riddle, :class => "delete", :method => 'delete', :data => {:confirm => 'Please confirm.'} %>

app/views/riddles/index.html.erb
<div>
    <div class="riddleindex">
            <h1 class="welcome">All Riddles</h1>

        <div class="listings">
            <% @riddles.each do |riddle|%>
                <% if riddle.user.present? %>
                    <p id="individual_link">
                    <%= link_to riddle.name, riddle %> <br> Author: <%= link_to riddle.user.email, riddle.user %> 
                    </p>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/riddles/new.html.erb
<h1 class="bouncingheadings">Make a new riddle </h1>

<%= render :partial => 'form' %>

app/views/riddles/show.html.erb
<div class="riddleshow">
    <h1 class="bouncingheadings"><%= @riddle.name %></h1>

    <h2> <%= @riddle.question %> </h2>

    <% if @flash_alert.present? %>
        <h1 class="flash"><%= @flash_alert %></h1>
    <% end %>

    <%= form_tag riddle_path(@riddle) do %>
        <%= label_tag :please_answer_below %>
        <%= text_field_tag :answer %>
        <%= submit_tag "Answer", :class => "answerbutton" %>
    <% end %>

    <% if @current_user.id == @riddle.user_id %>
        <%= link_to 'Edit Riddle', edit_riddle_path %>
    <% end %>
</div>

app/views/scores/edit.html.erb
<h1>Scores#edit</h1>
<p>Find me in app/views/scores/edit.html.erb</p>

app/views/scores/index.html.erb
<h1>Scores#index</h1>
<p>Find me in app/views/scores/index.html.erb</p>

app/views/scores/new.html.erb
<h1>Scores#new</h1>
<p>Find me in app/views/scores/new.html.erb</p>

app/views/scores/show.html.erb
<div class="coverup">
    <div class="congratulations">
        <h1>Thanks for playing</h1>
        <h2> Your score was <%= @score %> seconds</h2>
        <button class="view_score postbutton" >View all Scores</button>
    </div>
</div>

<div class="heading_score">
    <h1> <%= @riddle.name %> - Highscores </h1>
</div>

<div class="table_content">
<table>
    <tr>
        <th class="table_header" >Seconds</th>
        <th class="table_header" >User</th>
    </tr>

    <% @scores.each do |score| %>
        <% if score.riddle_id == @riddle.id  %>
            <tr class = "table_row">
                <td> <%= score.point %> </td>
                <td> <%= (@user.find (score.user_id)).email%> </td>
            </tr>
        <% end %>
    <% end %>
</table>
</div>

app/views/session/new.html.erb
<h1 class="bouncingheadings">Log in</h1>

<div class="error">
<% if flash[:error].present? %> 
    <h2><%= flash[:error] %></h2>
<% end %>
</div>

<%= form_tag login_path, :id => 'new_user' do %>
    <%= label_tag :email %>
    <%= email_field_tag :email %>

    <%= label_tag :password %>
    <%= password_field_tag :password %>

    <%= submit_tag "Sign in", :class => "postbutton" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.label :info %>
    <%= f.text_area :info, :class => "questionbox" %>

    <%= f.label :image %>
    <%= f.text_field :image %>

    <%= f.submit "Update", :class => "postbutton" %>
<% end %>

app/views/users/edit.html.erb
<h1 class ="bouncingheadings">Edit Profile</h1>

<%= render :partial => 'form' %>

app/views/users/index.html.erb
<div>
    <div class="riddleindex">
        <h1 class="welcome" >All Users</h1>

        <h2 class="welcome"><%= @users.count %> registered users</h2>
        <div class="adminlinks">
            <ul class="unordered">
                <% @users.each do |user| %>
                <p id="individual_link"><%= link_to user.email, user %></p>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1 class="bouncingheadings">Sign Up!</h1>

<div class="error">
    <% if @user.errors.any? %>
        <ol>
            <% @user.errors.full_messages.each do |msg| %>
                <h2><%= msg %></h2>
            <% end %>
        </ol>
    <% end %>
</div>


<%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    
    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :confirm_password %>
    <br>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign Up" , :class => "postbutton" %>

<% end %>

app/views/users/show.html.erb
<div class="userbody">
    <div class="profile" id="pinfo">
            <h1 class="welcome" id="pheading">Profile</h1>
            <h2 class="welcome" id="pheading"><%= @user.email%></h2>
            <%= image_tag @user.image, :class => 'pfp' if @user.image.present? %>
        <h3 class="info">Info</h3>
        <p class="blurb"><%= @user.info %></p>


        <%= link_to 'Edit Profile', edit_user_path if @current_user.id == @user.id%>
        <% if @current_user.admin? %>
        <%= button_to "Delete Profile", @user, :class => "delete", :method => 'delete', :data => {:confirm => 'Please confirm.'} %>
        <% end %>
    </div>
    <div class="profile" id="priddle">
        <div id="borderriddle"></div>
        <h1 class="welcome" id="pheading">Riddles</h1>
        <div class="riddlelinks">
            <% @user.riddles.each do |riddle| %>
                <p id="individual_link">
                    <%= link_to riddle.name, riddle %>
                </p>
            <% end %>
        </div>
    </div>
</div>